services:
  postgres:
    image: postgis/postgis:latest
    environment:
      - POSTGRES_DB=i-need-housing
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  keymaster_service:
    build:
      context: ./keymaster_service
      dockerfile: Dockerfile.dev
    ports:
      - "8083:8080"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/i-need-housing
    env_file:
      - ./keymaster_service/compose.env
    depends_on:
      - postgres

  new_listings_service:
    build: ./new_listings_service
    ports:
      - "8082:8080"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/i-need-housing
    env_file:
      - ./new_listings_service/compose.env
    depends_on:
      - postgres

  cron_job_service:
    build:
      context: ./cron_job_service
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8080"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/i-need-housing
    env_file:
      - ./cron_job_service/compose.env
    depends_on:
      - postgres

  ineedhousing_api:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/compose.env
    depends_on:
      - postgres

volumes:
  postgres-data: