version: "3.9"

services:
  postgres:
    image: postgis/postgis:latest
    environment:
      - POSTGRES_DB=i-need-housing
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist data

  keymaster_service:
    build: ./keymaster_service
    container_name: keymaster_service
    ports:
      - "8083:8080"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/i-need-housing
      - INEEDHOUSING_API_URL=http://ineedhousing_api:8080
    env_file:
      - ./keymaster_service/.env
    depends_on:
      - postgres

  new_listings_service:
    build: ./new_listings_service
    container_name: new_listings_service
    ports:
      - "8082:8080"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/i-need-housing
      - KEYMASTER_SERVICE_URL=http://keymaster_service:8080
    env_file:
      - ./new_listings_service/.env
    depends_on:
      - postgres

  cron_job_service:
    build: ./cron_job_service
    container_name: cron_job_service
    ports:
      - "8081:8080"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/i-need-housing
      - NEW_LISTINGS_SERVICE_ENDPOINT=http://new_listings_service:8080
      - KEYMASTER_SERVICE_URL=http://keymaster_service:8080
    env_file:
      - ./cron_job_service/.env
    depends_on:
      - postgres

  ineedhousing_api:
    build: .
    container_name: ineedhousing_api
    ports:
      - "8080:8080"
    environment:
      - CRON_JOB_SERVICE_URL=http://cron_job_service:8080
      - CRON_JOB_SERVICE_WEBSOCKET_ENDPOINT=ws://cron_job_service:8080/live-logs
      - KEYMASTER_SERVICE_URL=http://keymaster_service:8080
      - NEW_LISTINGS_SERVICE_URL=http://new_listings_service:8080
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/i-need-housing
    env_file:
      - ./backend/dev.env
    depends_on:
      - postgres

volumes:
  postgres-data:
