openapi: '3.0.3'
info:
  title: INeedHousing Backend Endpoints
  version: '1.0'
servers:
  - url: localhost:8080/
    description: Dev testing
  - url: ????/
    description: not sure yet

paths:
  /users/{email}:
    $ref: "./paths/users/email.yaml"
  

components:
  schemas:
    User:
      $ref: './schemas/user.yaml'
    UserPreference:
      $ref: './schemas/userPreferences.yaml'
    FavoriteListing:
      $ref: './schemas/favoriteListing.yaml'
    HousingListing:
      $ref: './schemas/listing.yaml'



