name: Deploy to Production

on:
  push:
    branches:
      - production
  workflow_dispatch: # Allow manual triggering

env:
  AZURE_CONTAINER_REGISTRY: ineedhousing.azurecr.io
  BACKEND_APP_SERVICE: i-need-housing-backend
  CRON_APP_SERVICE: cron-job-service
  RESOURCE_GROUP: INeedHousing

jobs:
  check-changes:
    name: Check for Changes
    runs-on: ubuntu-latest
    outputs:
      backend-changed: ${{ steps.changes.outputs.backend }}
      cron-changed: ${{ steps.changes.outputs.cron }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history for change detection
          
      - name: Check for changes in services
        id: changes
        run: |
          # Get the previous commit on production branch
          PREV_COMMIT=$(git rev-parse HEAD~1)
          CURRENT_COMMIT=$(git rev-parse HEAD)
          
          echo "Previous commit: $PREV_COMMIT"
          echo "Current commit: $CURRENT_COMMIT"
          
          # Check if backend has changes
          if git diff --name-only $PREV_COMMIT $CURRENT_COMMIT | grep -q "^backend/"; then
            echo "backend=true" >> $GITHUB_OUTPUT
            echo "✅ Backend has changes"
          else
            echo "backend=false" >> $GITHUB_OUTPUT
            echo "⏭️  No backend changes detected"
          fi
          
          # Check if cron service has changes
          if git diff --name-only $PREV_COMMIT $CURRENT_COMMIT | grep -q "^cron_job_service/"; then
            echo "cron=true" >> $GITHUB_OUTPUT
            echo "✅ Cron service has changes"
          else
            echo "cron=false" >> $GITHUB_OUTPUT
            echo "⏭️  No cron service changes detected"
          fi
          
          # Check if shared dependencies have changes
          if git diff --name-only $PREV_COMMIT $CURRENT_COMMIT | grep -q "^scripts/\|^pom.xml\|^Dockerfile"; then
            echo "🔄 Shared dependencies changed - will build both services"
            echo "backend=true" >> $GITHUB_OUTPUT
            echo "cron=true" >> $GITHUB_OUTPUT
          fi

  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.backend-changed == 'true'
    environment: prod-env
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo usermod -aG docker $USER
          
      - name: Login to Azure
        run: |
          az login --tenant ${{ secrets.AZURE_TENANT_ID }} -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }}
          
      - name: Login to Azure Container Registry
        run: |
          az acr login --name ineedhousing
          
      - name: Build and push backend image
        run: |
          cd backend
          # Generate unique timestamp tag
          TIMESTAMP=$(date +%s)
          IMAGE_NAME="ineedhousing.azurecr.io/images/backend:v$TIMESTAMP"
          
          # Build Docker image
          docker build -t $IMAGE_NAME .
          
          # Push to ACR
          docker push $IMAGE_NAME
          
          # Update App Service container settings
          az webapp config container set \
            --name ${{ env.BACKEND_APP_SERVICE }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --container-image-name $IMAGE_NAME \
            --container-registry-url https://${{ env.AZURE_CONTAINER_REGISTRY }}
            
          # Configure startup timeout
          az webapp config set \
            --name ${{ env.BACKEND_APP_SERVICE }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --generic-configurations '{"startupTimeLimit": 500}'
            
          # Restart App Service
          az webapp restart \
            --name ${{ env.BACKEND_APP_SERVICE }} \
            --resource-group ${{ env.RESOURCE_GROUP }}
            
          echo "Backend deployment completed successfully"
          
  deploy-cron-service:
    name: Deploy Cron Job Service
    runs-on: ubuntu-latest
    needs: [check-changes, deploy-backend]
    if: needs.check-changes.outputs.cron-changed == 'true'
    environment: prod-env
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo usermod -aG docker $USER
          
      - name: Login to Azure
        run: |
          az login --tenant ${{ secrets.AZURE_TENANT_ID }} -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }}
          
      - name: Login to Azure Container Registry
        run: |
          az acr login --name ineedhousing
          
      - name: Build and push cron service image
        run: |
          cd cron_job_service
          # Generate unique timestamp tag
          TIMESTAMP=$(date +%s)
          IMAGE_NAME="ineedhousing.azurecr.io/images/cron_job_service:v$TIMESTAMP"
          
          # Build Docker image
          docker build -t $IMAGE_NAME .
          
          # Push to ACR
          docker push $IMAGE_NAME
          
          # Update App Service container settings
          az webapp config container set \
            --name ${{ env.CRON_APP_SERVICE }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --container-image-name $IMAGE_NAME \
            --container-registry-url https://${{ env.AZURE_CONTAINER_REGISTRY }}
            
          # Configure startup timeout
          az webapp config set \
            --name ${{ env.CRON_APP_SERVICE }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --generic-configurations '{"startupTimeLimit": 500}'
            
          # Restart App Service
          az webapp restart \
            --name ${{ env.CRON_APP_SERVICE }} \
            --resource-group ${{ env.RESOURCE_GROUP }}
            
          echo "Cron service deployment completed successfully"
          
  deployment-summary:
    name: Deployment Summary
    runs-on: ubuntu-latest
    needs: [check-changes, deploy-backend, deploy-cron-service]
    if: always()
    
    steps:
      - name: Check deployment status
        run: |
          echo "=== Deployment Summary ==="
          echo "Backend changes detected: ${{ needs.check-changes.outputs.backend-changed }}"
          echo "Cron service changes detected: ${{ needs.check-changes.outputs.cron-changed }}"
          echo ""
          
          # Check backend deployment status
          if [ "${{ needs.check-changes.outputs.backend-changed }}" == "true" ]; then
            if [ "${{ needs.deploy-backend.result }}" == "success" ]; then
              echo "✅ Backend deployed successfully"
            else
              echo "❌ Backend deployment failed"
            fi
          else
            echo "⏭️  Backend skipped (no changes)"
          fi
          
          # Check cron service deployment status
          if [ "${{ needs.check-changes.outputs.cron-changed }}" == "true" ]; then
            if [ "${{ needs.deploy-cron-service.result }}" == "success" ]; then
              echo "✅ Cron service deployed successfully"
            else
              echo "❌ Cron service deployment failed"
            fi
          else
            echo "⏭️  Cron service skipped (no changes)"
          fi
          
          echo ""
          echo "=== Final Status ==="
          
          # Determine overall success
          if [ "${{ needs.check-changes.outputs.backend-changed }}" == "false" ] && [ "${{ needs.check-changes.outputs.cron-changed }}" == "false" ]; then
            echo "🎉 No changes detected - no deployment needed!"
            exit 0
          elif [ "${{ needs.deploy-backend.result }}" == "success" ] || [ "${{ needs.deploy-backend.result }}" == "skipped" ]; then
            if [ "${{ needs.deploy-cron-service.result }}" == "success" ] || [ "${{ needs.deploy-cron-service.result }}" == "skipped" ]; then
              echo "🎉 All required deployments completed successfully!"
              exit 0
            else
              echo "❌ Some deployments failed"
              exit 1
            fi
          else
            echo "❌ Some deployments failed"
            exit 1
          fi 